# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'yahiiMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for yahiiMobile

  # target 'yahiiMobile-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket'
  ]

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # target 'yahiiMobileTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

# target 'yahiiMobile-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for yahiiMobile-tvOS

#   target 'yahiiMobile-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
